import { fruits, biscuits, milkproducts, snacks, meals } from "@/app/constants";
export const data = [
  {
    id: 1,
    name: "Organic Mixed Fruits Pack",
    category: "Fruits",
    price: 499,
    originalPrice: 699,
    discount: 25,
    rating: 4.5,
    image: fruits,
  },
  {
    id: 2,
    name: "Premium Cookies ",
    category: "Biscuits",
    price: 299,
    originalPrice: 399,
    discount: 20,
    rating: 4.8,
    image: biscuits,
  },
  {
    id: 3,
    name: "Fresh Dairy Products Pack",
    category: "Milk Products",
    price: 399,
    originalPrice: 599,
    discount: 30,
    rating: 4.6,
    image: milkproducts,
  },
  {
    id: 4,
    name: "Healthy Snacks Combo",
    category: "Snacks",
    price: 449,
    originalPrice: 649,
    discount: 35,
    rating: 4.7,
    image: snacks,
  },
  {
    id: 5,
    name: "Ready-to-Eat Meals Box",
    category: "Meals",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.4,
    image: meals,
  },
];
